export const OG_NAMES = [
  "Belmondo",
  "Młody G",
  "Młody Sarmata",
  "Obywatel bez NIPu",
  "Obywatel Meksyku",
  "Młody Bonaparte tylko że naprawdę",
  "Nowy Napoleon tylko większe berło",
  "Psychodeliczny wiking",
  "Młody Kmicic",
  "George Orwell z bongiem",
  "Sportowiec",
  "Kolega od jebanka",
  "Scrooge Ebenezer",
  "Sztosinger",
  "Dr Traphałs",
  "Belmondawg",
  "Czarodziej z Oz",
  "Urwipołeć śmierdzący groszem",
  "Muszkieter",
  "Ostateczny nurt",
  "Tytus",
  "Inspektor Gadżet",
  "Bojkot",
  "Nowy Tony Hawk tylko że rapowy",
  "Młody Gypsy",
  "Atlas",
  "Młody Mastermind",
  "Młody Glitch",
  "Młody Snake Plissken",
  "Młody Rastafari",
  "Tyti",
  "Młody Gdynianin",
  "Młody Mowgli",
  "Belmondziarz",
  "Belmondziak Sztosinger",
  "G",
  "Daquan",
  "Młody Muchadore",
  "Młody G z Gdyni",
  "Hajle Syllasje",
  "Mowgli Wychowanek Dżungli",
  "Młody figlarz",
  "Keepercipek",
  "Husky",
  "Młody Scrooge McDuck",
  "Młody Libertarianin",
  "Syn Ayn",
  "Algidziak",
  "Młody Algida",
  "Proteziak",
  "Nowy Larry Flynt",
  "฿elmondœ",
  "Młody Stavro Blofeld",
  "Liroy Merlin",
  "Mobbyn Ranger",
  "Nowy Orson Welles",
  "Młody Bi",
  "Młody G Sportowiec",
  "Młody Gypsy",
  "Młody G z Gdyni i nie z Kambodży",
  "Młody G z Gdyni a nie z Nairobi",
  "Młody G z Gdyni a nie z Francji",
  "Sułtan",
];

export const BASE_NAMES = [
  "Belmondo",
  "G",
  "Sarmata",
  "Bonaparte",
  "Napoleon",
  "wiking",
  "Kmicic",
  "George Orwell",
  "Sportowiec",
  "Kolega",
  "Scrooge Ebenezer",
  "Sztosinger",
  "Traphałs",
  "Belmondawg",
  "Czarodziej",
  "Urwipołeć",
  "Muszkieter",
  "Ostateczny nurt",
  "Tytus",
  "Inspektor Gadżet",
  "Bojkot",
  "Tony Hawk",
  "Gypsy",
  "Atlas",
  "Mastermind",
  "Glitch",
  "Snake Plissken",
  "Rastafari",
  "Tyti",
  "Gdynianin",
  "Mowgli",
  "Belmondziarz",
  "Belmondziak Sztosinger",
  "G",
  "Daquan",
  "Muchadore",
  "Hajle Syllasje",
  "Mowgli",
  "figlarz",
  "Keepercipek",
  "Husky",
  "Scrooge McDuck",
  "Libertarianin",
  "Syn Ayn",
  "Algidziak",
  "Algida",
  "Proteziak",
  "Larry Flynt",
  "฿elmondœ",
  "Stavro Blofeld",
  "Liroy Merlin",
  "Mobbyn Ranger",
  "Orson Welles",
  "Bi",
  "Sułtan",
];

export const PRE_NAMES = [
  "Młody",
  "Młody Dr",
  "Obywatel",
  "Nowy",
  "Psychodeliczny",
  "Dr",
  "Ostateczny",
  "Inspektor",
];

export const POST_NAMES = [
  "bez NIPu",
  "tylko że naprawdę",
  "tylko większe berło",
  "z bongiem",
  "od jebanka",
  "z Oz",
  "śmierdzący groszem",
  "tylko że rapowy",
  "Sztosinger",
  "z Gdyni",
  "Wychowanek Dżungli",
  "figlarz",
  "Proteziak",
  "Sportowiec",
  "z Gdyni nie z Kambodży",
  "z Gdyni a nie z Nairobi",
  "z Gdyni a nie z Francji",
  "Sułtan",
];
